<?php
return [
    'process' => [
        'Admin_Lock' => [
            'option' => 'direct',
            'value' => 'Check BIOS Status',
        ],
        'Bad_Backlight' => [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Bad_Battery' =>[
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Bad_Display' => [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Bad_Fan' => [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Bad_Keyboard' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Bad_Optical_Drive' => 
        [
            'option' => '',
            'Yes' => 'Add to Holding Pallet',
            'No' => '',
        ],
        'Bad_Power_Supply_x_1' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Bad_Power_Supply_x_2' => 
        [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'Bad_Trackpad' => 
        [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'BIOS_Lock' => 
        [
            'option' => 'direct',
            'value' => 'Check BIOS Status',
        ],
        'Broken_Hinge' => 
        [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'Broken_Port_(Network)' => 
        [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'Broken_Port_(Power)' => 
        [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'Broken_Port_(USB)' => 
        [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'Broken_Port_(Video)' => 
        [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'Caddy' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Case_Dent_Minor' => 
        [
            'option' => 'direct',
            'value' => 'Requires Bondo',
        ],
        'Case_Dent_Severe' => 
        [
            'option' => 'direct',
            'value' => 'Requires Bondo',
        ],
        'Case_Discolor' => 
        [
            'option' => 'direct',
            'value' => 'Requires Paint',
        ],
        'Case_Scratch_Minor' => 
        [
            'option' => 'direct',
            'value' => 'Requires Paint',
        ],
        'Case_Scratch_Severe' => 
        [
            'option' => 'direct',
            'value' => 'Requires Paint',
        ],
        'Chassis_Cover' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Computrace_Pending' => 
        [
            'option' => 'direct',
            'value' => 'Check BIOS Status',
        ],
        'CPU_Fan' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Cracked_Case_Minor' => 
        [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'Cracked_Case_Severe' => 
        [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'Cracked_Screen_Major' => 
        [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'Cracked_Screen_Minor' => 
        [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'Damaged_Case_Release' => 
        [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'Dark_Screen' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Dead_Pixel_Minor' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Dead_Pixel_Severe' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Does_Not_Boot' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Faceplate' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Fan_Error' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Hard_Drive_Cover' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'HDD_Screws' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Laptop_Missing Description_Key(s)' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'LCD_Screen' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Memory_Cover' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Missing Description_Buttons' => 
        [
            'option' => 'direct',
            'value' => 'X',
        ],
        'No_COA' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'No_Display' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'No_Keyboard' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Missing_Key(s)' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Power_button' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Pressure_Mark_Minor' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Pressure_Mark_Severe' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Rack_Rails' => 
        [
            'option' => 'direct',
            'value' => 'X',
        ],
        'Raid_Controller_Error' => 
        [
            'option' => 'direct',
            'value' => 'X',
        ],
        'Rear_Cover' => 
        [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Rubber_Feet' => 
        [
            'option' => 'direct',
            'value' => 'Add Rubber Feet',
        ],
        'Screen_Burn_Minor' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Screen_Burn_Severe' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Screen_Lines_Minor' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Screen_Lines_Severe' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Screen_Scratch_Minor' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Screen_Scratch_Severe' => 
        [
            'option' => 'direct',
            'value' => 'Add to Holding Pallet',
        ],
        'Screws' => [
            'option' => 'direct',
            'value' => 'Add Case Screws',
        ],
        'Security_Plate' => [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Serial_Number' => [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Stand/Base' => [
            'option' => 'direct',
            'value' => 'X',
        ],
        'Water_Damage' => [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'Will_Not_Power_On' => [
            'option' => 'direct',
            'value' => 'Add to Wholesale Pallet',
        ],
        'Worn_COA' => [
            'option' => '',
            'Yes' => '',
            'No' => '',
        ],
        'Worn_Trackpad' =>[
            'option' => 'direct',
            'value' => 'Skin Interior',
        ],
        'Worn Handrest' => [
            'option' => 'direct',
            'value' => 'Skin Interior',
        ],
        'is_laptop' =>[
            'option' => 'direct',
            'value' => 'Needs to be Skinned',
        ],
        'Requires Skin' =>[
            'option' => 'direct',
            'value' => 'Needs to be Skinned',
        ],
    ],
    'controlTypes' => [
        "text" => "Text field",
        "area" => "Text area",
        "number" => "Numeric field",
        "dropdown" => "Dropdown list",
        "radio" => "Radio items",
        "mult" => "Checkbox items",
        "bool" => "Single checkbox"
    ],
    'damageScores' => [
        "Cracked_Case_Severe" => 10,
        "Cracked_Screen_Severe" => 10,
        "Does_Not_Boot" => 10,
        "Pressure_Mark_Severe" => 10,
        "Screen_Burn_Severe" => 10,
        "Screen_Lines_Severe" => 10,
        "Water_Damage" => 10,
        "Will_Not_Power_On" => 10,
        "Dead_Pixel_Severe" => 10,
        "LCD_Screen" => 10,
        "Bad_Display" => 8,
        "No_Display" => 8,
        "Cracked_Screen_Minor" => 8,
        "Screen_Scratch_Severe" => 7,
        "Case_Dent_Severe" => 7,
        "Admin_Lock" => 5,
        "BIOS_Lock" => 5,
        "Broken_Port_(Network)" => 5,
        "Broken_Port_(Power)" => 5,
        "Broken_Port_(USB)" => 5,
        "Broken_Port_(Video)" => 5,
        "Dead_Pixel_Minor" => 5,
        "No_Keyboard" => 5,
        "Pressure_Mark_Minor" => 5,
        "Screen_Burn_Minor" => 5,
        "Screen_Lines_Minor" => 5,
        "Bad_Keyboard" => 5,
        "Stand/Base" => 5,
        "Chassis_Cover" => 3,
        "Broken_Hinge" => 3,
        "Case_Scratch_Severe" => 3,
        "Damaged_Case_Release" => 3,
        "Security_Plate" => 3,
        "Bad_Backlight" => 3,
        "Bad_Trackpad" => 3,
        "CPU_Fan" => 3,
        "Bad_Fan" => 2,
        "Case_Dent_Minor" => 2,
        "Dark_Screen" => 2,
        "Fan_Error" => 2,
        "Faceplate" => 2,
        "Raid_Controller_Error" => 2,
        "Worn_Trackpad" => 2,
        "Power_Button" => 2,
        "Rear_Cover" => 2,
        "Buttons_Other" => 1,
        "Bad_Battery" => 1,
        "Computrace_Pending" => 1,
        "Bad_Power_Supply_x_1" => 1,
        "Bad_Power_Supply_x_2" => 1,
        "Case_Discolor" => 1,
        "Case_Scratch_Minor" => 1,
        "HD_2.5" => 1,
        "HD_3.5" => 1,
        "Screen_Scratch_Minor" => 1,
        "Rack_Rails" => 1,
        "Missing_Key(s)" => 1,
        "Caddy" => 0,
        "Hard_Drive_Cover" => 0,
        "HDD_Screws" => 0,
        "Bad_Optical_Drive" => 0,
        "Memory_Cover" => 0,
        "Rubber_Foot" => 0,
        "No_COA" => 0,
        "Screws" => 0,
        "Serial_Number" => 0,
        "Worn_COA" => 0
    ],
    'descrTypes' => [
        "Admin_Lock" => "Functional",
        "Bad_Backlight" => "Functional",
        "Bad_Battery" => "Functional",
        "Bad_Display" => "Functional",
        "Bad_Fan" => "Functional",
        "Bad_Keyboard" => "Functional",
        "Bad_Optical_Drive" => "Functional",
        "Bad_Power_Supply_x_1" => "Functional",
        "Bad_Power_Supply_x_2" => "Functional",
        "Bad_Trackpad" => "Functional",
        "BIOS_Lock" => "Functional",
        "Broken_Hinge" => "Cosmetic",
        "Broken_Port_(Network)" => "Cosmetic",
        "Broken_Port_(Power)" => "Cosmetic",
        "Broken_Port_(USB)" => "Cosmetic",
        "Broken_Port_(Video)" => "Cosmetic",
        "Caddy" => "Missing",
        "Case_Dent_Minor" => "Cosmetic",
        "Case_Dent_Severe" => "Cosmetic",
        "Case_Discolor" => "Cosmetic",
        "Case_Scratch_Minor" => "Cosmetic",
        "Case_Scratch_Severe" => "Cosmetic",
        "Chassis_Cover" => "Missing",
        "Computrace_Pending" => "Notes",
        "CPU_Fan" => "Missing",
        "Cracked_Case_Minor" => "Cosmetic",
        "Cracked_Case_Severe" => "Cosmetic",
        "Cracked_Screen_Major" => "Cosmetic",
        "Cracked_Screen_Minor" => "Cosmetic",
        "Damaged_Case_Release" => "Cosmetic",
        "Dark_Screen" => "Cosmetic",
        "Dead_Pixel_Minor" => "Functional",
        "Dead_Pixel_Severe" => "Functional",
        "Does_Not_Boot" => "Functional",
        "Faceplate" => "Missing",
        "Fan_Error" => "Functional",
        "Hard_Drive_Cover" => "Missing",
        'HD_2.5"' => "Notes",
        'HD_3.5"' => "Notes",
        "HDD_Screws" => "Missing",
        "Laptop_Missing Description_Key(s)" => "Missing",
        "LCD_Screen" => "Missing",
        "Memory_Cover" => "Missing",
        "Missing Description_Buttons" => "Missing",
        "No_COA" => "Missing",
        "No_Display" => "Functional",
        "No_Keyboard" => "Missing",
        "Missing_Key(s)" => "Missing",
        "Power_button" => "Missing",
        "Pressure_Mark_Minor" => "Functional",
        "Pressure_Mark_Severe" => "Functional",
        "Rack_Rails" => "Missing",
        "Raid_Controller_Error" => "Functional",
        "Rear_Cover" => "Missing",
        "Rubber_Feet" => "Missing",
        "Screen_Burn_Minor" => "Functional",
        "Screen_Burn_Severe" => "Functional",
        "Screen_Lines_Minor" => "Functional",
        "Screen_Lines_Severe" => "Functional",
        "Screen_Scratch_Minor" => "Functional",
        "Screen_Scratch_Severe" => "Functional",
        "Screws" => "Missing",
        "Security_Plate" => "Cosmetic",
        "Serial_Number" => "Missing",
        "Stand/Base" => "Missing",
        "Water_Damage" => "Functional",
        "Will_Not_Power_On" => "Functional",
        "Worn_COA" => "Cosmetic",
        "Worn_Trackpad" => "Cosmetic"
    ],
    'shipmentEmails' => [
        "rahuls.techmarbles@gmail.com",
        // "randy@itamg.com",
        // "richy@itamg.com",
        // "support@refurbconnect.com",
        // "diego@refurbconnect.com",
        // "taylor@refurbconnect.com",
        // "richard@itamg.com",
        // "julio@itamg.com",
    ],
    'sessionEmails ' => [
        "rahuls.techmarbles@gmail.com",
        // "randy@itamg.com",
        // "richy@itamg.com",
        // "support@refurbconnect.com",
        // "diego@refurbconnect.com",
        // "taylor@refurbconnect.com",
        // "richard@itamg.com",
        // "julio@itamg.com",
    ],
    'auditRefurbBlacklist' => [
        "Case_Engraved",
        "Managed",
        "Worn_Keys_Severe",
        "Keyboard_Keys",
        "Power_Button",
        "Case_Dent_Top_Cover_Minor"
    ],
    'auditDamageScores' => [
        "Security_Plate"=>0,
        "Worn_COA"=>0,
        "Case_Engraved"=>0,
        "Worn_Serial_Number"=>0,
        "Case_Discolor"=>1,
        "Case_Scratch_Minor"=>1,
        "Case_Dent_Minor"=>6,
        "Bottom_Panel"=>6,
        "Broken_Hinge"=>6,
        "Case_Scratch_Severe"=>6,
        "Damaged_Case_Release"=>6,
        "Chassis_Cover"=>6,
        "Case_Dent_Severe"=>11,
        "Cracked_Case_Severe"=>11,
        "Cracked_Case_Minor"=>8,
        "Cracked_Face_Plate"=>8,
        "Damaged_Bezel"=>8,
        "Damaged_Bracket"=>8,
        "Latch_Will_Not_Close (Laptop)"=>8,
        "Loose_Hinges"=>8,
        "Side_Panel"=>6,
        "Back_Panel"=>6,
        "Defective_Memory"=>0,
        "Defective_Power_Supply"=>0,
        "Defective_Power_Supply_x_1"=>0,
        "Defective_Power_Supply_x_2"=>0,
        "Managed"=>0,
        "Unmanaged"=>0,
        "Fan_Error"=>6,
        "Raid_Controller_Error"=>1,
        "CPU_Fan"=>6,
        "BIOS_Lock"=>6,
        "Admin_Lock"=>6,
        "Defective_Capacitors"=>8,
        "Does_Not_Boot"=>11,
        "Does_Not_Power_On"=>11,
        "Water_Damage"=>11,
        "Defective_CPU"=>11,
        "Barebone"=>11,
        "Defective_Fan"=>11,
        "Defective_Fuser"=>11,
        "Defective_Motherboard"=>11,
        "Defective_Raid_Controller"=>6,
        "Defective_Roller"=>6,
        "Defective_WiFi"=>8,
        "iCloud_Locked"=>11,
        "Low_Lamp_Life"=>8,
        "Missing_Image_File"=>8,
        "Missing_Image_VoIP"=>8,
        "Printer_Error"=>6,
        "Worn_Trackpad"=>0,
        "Worn_Keys_Severe"=>0,
        "Defective_Optical_Drive"=>0,
        "Defective_Video_Card"=>0,
        "Broken_Port_(Network)"=>11,
        "Broken_Port_(Power)"=>11,
        "Broken_Port_(USB)"=>11,
        "Broken_Port_(Video)"=>11,
        "Bent_Port_(Network)"=>6,
        "Bent_Port_(SFP)"=>6,
        "Broken_Port_(SFP)"=>11,
        "Broken_Port_(VGA)"=>11,
        "Defective_Keyboard"=>6,
        "Defective_Port_(Network)"=>11,
        "Defective_Port_(Power)"=>11,
        "Defective_Port_(SFP)"=>11,
        "Defective_Port_(USB)"=>11,
        "Defective_Port_(VGA)"=>11,
        "Defective_Port_(Video)"=>11,
        "Defective_Trackpad"=>6,
        "Caddy"=>0,
        "Hard_Drive_Cover"=>0,
        "HDD_Screws"=>0,
        "Memory_Cover"=>0,
        "Screws"=>0,
        "Serial_Number"=>0,
        "Bumpers"=>0,
        "Cables"=>0,
        "Caddy_Rail"=>0,
        "Faceplate"=>0,
        "Hard_Drive_Blanks_x_"=>0,
        "Keyboard_Keys"=>0,
        "LCD_Stand"=>6,
        "Port_Cover"=>0,
        "Power_Supply_x_1"=>0,
        "Power_Supply_x_2"=>0,
        "Power_Supply_x_3"=>0,
        "Power_Supply_x_4"=>0,
        "Rubber_Feet"=>0,
        "Stylus"=>0,
        "Power_Button"=>1,
        "Stand/Base"=>6,
        "Antenna"=>6,
        "Buttons"=>3,
        "Fuser"=>3,
        "Keyboard_(Laptops)"=>6,
        "NAND/Flash"=>6,
        "Raid_Controller"=>6,
        "Computrace_Pending"=>0,
        "Screen_Scratch_Minor"=>2,
        "Dark_Screen"=>6,
        "Dead_Pixel_Minor"=>5,
        "Pressure_Mark_Minor"=>5,
        "Screen_Burn_Minor"=>5,
        "Screen_Lines_Minor"=>5,
        "Defective_Backlight"=>6,
        "Screen_Scratch_Severe"=>7,
        "Cracked_Screen_Minor"=>8,
        "No_Display"=>8,
        "Cracked_Screen_Severe"=>10,
        "Dead_Pixel_Severe"=>10,
        "Pressure_Mark_Severe"=>10,
        "Screen_Burn_Severe"=>10,
        "Screen_Lines_Severe"=>10,
        "Cracked_Screen"=>11,
        "Defective_Display"=>11,
        "Defective_Touch_Screen"=>11,
        "No_LCD"=>11,
        "Cracked_Front_Glass_Minor"=>5,
        "Cracked_Front_Glass_Severe"=>5,
        "Chipped_Front_Glass_Severe"=>5,
        "Chipped_Front_Glass_Minor"=>5,
        "Missing_Front_Glass"=>6,
        "Case_Dent_Top_Cover_Minor"=>2,
        "Case_Dent_Top_Cover_Severe"=>6,
        "Case_Dent_Coner_Minor"=>6,
        "Case_Dent_Coner_Severe"=>11
    ],
    'auditDescrTypes' => [
        "Worn_COA"=>"Cosmetic",
        "Security_Plate"=>"Cosmetic",
        "Case_Engraved"=>"Cosmetic",
        "Worn_Serial_Number"=>"Cosmetic",
        "Case_Discolor"=>"Cosmetic",
        "Case_Scratch_Minor"=>"Cosmetic",
        "Case_Dent_Minor"=>"Cosmetic",
        "Bottom_Panel"=>"Missing",
        "Broken_Hinge"=>"Cosmetic",
        "Case_Scratch_Severe"=>"Cosmetic",
        "Damaged_Case_Release"=>"Cosmetic",
        "Chassis_Cover"=>"Missing",
        "Case_Dent_Severe"=>"Cosmetic",
        "Cracked_Case_Severe"=>"Cosmetic",
        "Cracked_Case_Minor"=>"Cosmetic",
        "Cracked_Face_Plate"=>"Cosmetic",
        "Damaged_Bezel"=>"Cosmetic",
        "Damaged_Bracket"=>"Cosmetic",
        "Latch_Will_Not_Close (Laptop)"=>"Cosmetic",
        "Loose_Hinges"=>"Cosmetic",
        "Side_Panel"=>"Missing",
        "Back_Panel"=>"Missing",
        "Defective_Memory"=>"Functional",
        "Defective_Power_Supply"=>"Functional",
        "Defective_Power_Supply_x_1"=>"Functional",
        "Defective_Power_Supply_x_2"=>"Functional",
        "Managed"=>"Functional",
        "Unmanaged"=>"Functional",
        "Fan_Error"=>"Functional",
        "Raid_Controller_Error"=>"Functional",
        "CPU_Fan"=>"Functional",
        "BIOS_Lock"=>"Functional",
        "Admin_Lock"=>"Functional",
        "Defective_Capacitors"=>"Functional",
        "Does_Not_Boot"=>"Functional",
        "Does_Not_Power_On"=>"Functional",
        "Water_Damage"=>"Functional",
        "Defective_CPU"=>"Functional",
        "Barebone"=>"Functional",
        "Defective_Fan"=>"Functional",
        "Defective_Fuser"=>"Functional",
        "Defective_Motherboard"=>"Functional",
        "Defective_Raid_Controller"=>"Functional",
        "Defective_Roller"=>"Functional",
        "Defective_WiFi"=>"Functional",
        "iCloud_Locked"=>"Functional",
        "Low_Lamp_Life"=>"Functional",
        "Missing_Image_File"=>"Functional",
        "Missing_Image_VoIP"=>"Functional",
        "Printer_Error"=>"Functional",
        "Worn_Trackpad"=>"Cosmetic",
        "Worn_Keys_Severe"=>"Cosmetic",
        "Defective_Optical_Drive"=>"Functional",
        "Defective_Video_Card"=>"Functional",
        "Broken_Port_(Network)"=>"Functional",
        "Broken_Port_(Power)"=>"Functional",
        "Broken_Port_(USB)"=>"Functional",
        "Broken_Port_(Video)"=>"Functional",
        "Bent_Port_(Network)"=>"Functional",
        "Bent_Port_(SFP)"=>"Functional",
        "Broken_Port_(SFP)"=>"Functional",
        "Broken_Port_(VGA)"=>"Functional",
        "Defective_Keyboard"=>"Functional",
        "Defective_Port_(Network)"=>"Functional",
        "Defective_Port_(Power)"=>"Functional",
        "Defective_Port_(SFP)"=>"Functional",
        "Defective_Port_(USB)"=>"Functional",
        "Defective_Port_(VGA)"=>"Functional",
        "Defective_Port_(Video)"=>"Functional",
        "Defective_Trackpad"=>"Functional",
        "Caddy"=>"Missing",
        "Hard_Drive_Cover"=>"Missing",
        "HDD_Screws"=>"Missing",
        "Memory_Cover"=>"Missing",
        "Screws"=>"Missing",
        "Serial_Number"=>"Missing",
        "Bumpers"=>"Missing",
        "Cables"=>"Missing",
        "Caddy_Rail"=>"Missing",
        "Faceplate"=>"Missing",
        "Hard_Drive_Blanks_x_"=>"Missing",
        "Keyboard_Keys"=>"Missing",
        "LCD_Stand"=>"Missing",
        "Port_Cover"=>"Missing",
        "Power_Supply_x_1"=>"Missing",
        "Power_Supply_x_2"=>"Missing",
        "Power_Supply_x_3"=>"Missing",
        "Power_Supply_x_4"=>"Missing",
        "Rubber_Feet"=>"Missing",
        "Stylus"=>"Missing",
        "Power_Button"=>"Missing",
        "Stand/Base"=>"Missing",
        "Antenna"=>"Missing",
        "Buttons"=>"Missing",
        "Fuser"=>"Missing",
        "Keyboard_(Laptops)"=>"Missing",
        "NAND/Flash"=>"Missing",
        "Raid_Controller"=>"Missing",
        "Computrace_Pending"=>"Notes",
        "Screen_Scratch_Minor"=>"Functional",
        "Dark_Screen"=>"Functional",
        "Dead_Pixel_Minor"=>"Functional",
        "Pressure_Mark_Minor"=>"Functional",
        "Screen_Burn_Minor"=>"Functional",
        "Screen_Lines_Minor"=>"Functional",
        "Defective_Backlight"=>"Functional",
        "Screen_Scratch_Severe"=>"Functional",
        "Cracked_Screen_Minor"=>"Functional",
        "No_Display"=>"Functional",
        "Cracked_Screen_Severe"=>"Functional",
        "Dead_Pixel_Severe"=>"Functional",
        "Pressure_Mark_Severe"=>"Functional",
        "Screen_Burn_Severe"=>"Functional",
        "Screen_Lines_Severe"=>"Functional",
        "Cracked_Screen"=>"Functional",
        "Defective_Display"=>"Functional",
        "Defective_Touch_Screen"=>"Functional",
        "No_LCD"=>"Functional",
        "Cracked_Front_Glass_Minor"=>"Cosmetic",
        "Cracked_Front_Glass_Severe"=>"Cosmetic",
        "Chipped_Front_Glass_Severe"=>"Cosmetic",
        "Chipped_Front_Glass_Minor"=>"Cosmetic",
        "Missing_Front_Glass"=>"Cosmetic",
        "Case_Dent_Top_Cover_Minor"=>"Cosmetic",
        "Case_Dent_Top_Cover_Severe"=>"Cosmetic",
        "Case_Dent_Coner_Minor"=>"Cosmetic",
        "Case_Dent_Coner_Severe"=>"Cosmetic"
    ],
    'adminEmail' =>[
        "rahuls.techmarbles@gmail.com",
        // "asovych@gmail.com"
    ],
    'finalPriceConstants' => [
        'priceMargin' => 1.25,
        'processingCost' => 35,
        'ramCost' => 14,
        'hdCost' => 14.4,
        'osCost' => 30,
        'imagePath' => 'asin-images/',
        'imagePathNew' => 'asin-images/dropbox/Shopify_Images/',
        'condition' => 'A',
        'shopifyBaseUrl' => 'https://14a2e3d9e7a3661419a88549b45aa63e:11305811ff0dcf66770d9a9e7e3d80ef@what-does-refurbished-mean.myshopify.com',
        'productMainSiteUrl' => 'https://refurbconnection.com/products',
    ],
    'manuFacturer' => [
        'dell' => 'Dell',
        'inspiron' => 'Dell',
        'latitude' => 'Dell',
        'optiplex' => 'Dell',
        'precision' => 'Dell',
        'vostro' => 'Dell',
        'xps' => 'Dell',
        'hp' => 'HP',
        'elite' => 'HP',
        'elitebook' => 'HP',
        'elitedesk' => 'HP',
        'probook' => 'HP',
        'prodesk' => 'HP',
        'touchsmart' => 'HP',
        'workstation' => 'HP',
        'z200' => 'HP',
        'z210' => 'HP',
        'z400' => 'HP',
        'z440' => 'HP',
        'z820' => 'HP',
        'compaq' => 'HP',
        'lenovo' => 'Lenovo',
        'thinkcentre' => 'Lenovo',
        'thinkpad' => 'Lenovo',
        'apple' => 'Apple',
        'macbook' => 'Apple',
        'imac' => 'Apple',
        'macpro' => 'Apple',
    ],
    'syncProductAddedMailUser' => [
        'rahuls.techmarbles@gmail.com',
        // 'randy@itamg.com',
        // 'richy@refurbconnect.com',
        // 'ayaz_akhtar21@hotmail.com'
    ],
    'adminUsers' => [
        'admin',
        'randy'
    ],
    'recycleReportMailAddress' => [
        "rahuls.techmarbles@gmail.com",
        // "randy@itamg.com",
        // "julio@itamg.com",
        // "richy@itamg.com",
        // "kamal@itamg.com",
        // "matthew@itamg.com",
    ]
];